# Generated by Django 4.0.2 on 2022-02-19 14:36

from django.db import migrations, models
import pestagram1.main.validators


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_petphoto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petphoto',
            name='photo',
            field=models.ImageField(upload_to='pet_photos/', validators=[pestagram1.main.validators.file_max_size]),
        ),
        migrations.AlterField(
            model_name='profile',
            name='birth_date',
            field=models.DateField(blank=True, null=True, validators=[pestagram1.main.validators.correct_date]),
        ),
    ]
